version: '3'
services:
  movies:
    image: prasadpotla/projectmovies:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

  train:
    image: prasadpotla/projecttrain:latest
    ports:
      - "85:80"
    deploy:
      replicas: 3

  bus:
    image:  prasadpotla/projectbus:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3

