version: '3'
services:
  movies:
    image: vishnu155/bus:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: vishnu155/air:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: vishnu155/metro:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

