version: '3'
services:
  movies:
    image: vishnu155/projectmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: prasadpotla/projecttrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image:  prasadpotla/projectbus:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

